[package]
name = "untitled30xx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
inflate = "0.4.5"
deflate = "1.0.0"
crc32fast = "1.3.2"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
argh = "0.1.9"